# This CI job installs Crystal and shard dependencies, then executes `crystal spec` to run the test suite
# More configuration options are available at https://crystal-lang.github.io/install-crystal/configurator.html

on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 6" # Every Saturday 6 AM
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "v1.16"
          - "v1.17"
          - "v1.18"
          - "v1.19"
          - "v1.20"
          - "v1.22"
        include:
          - os: ubuntu-latest
          - os: ubuntu-latest
            crystal: 1.2.2
    runs-on: ${{ matrix.os }}
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - uses: rinx/setup-k3d@v0.0.2
        with:
          skipClusterCreation: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Install shards
        run: shards update --ignore-crystal-version
      - name: Setup k3s cluster
        run: k3d cluster create --k3s-server-args="--disable-agent" -c ./spec/files/k3d/${{ matrix.k8s }}.yml
      - name: Tear down cluster
        run: k3d cluster delete k3d-cluster-test
